Replacement tile can be null
The following log message was sent where it was shown a piston head may
cannot create a new tile, thus resulting in a fatal
`NullPointerException`:

```
[18:39:21] [Server thread/ERROR]: Block at 8 311, 31, -85 is Block{minecraft:moving_piston} but has net.minecraft.server.v1_16_R3.TileEntityFurnaceFurnace@157e066a. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
[18:39:21] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:53204
net.minecraft.server.v1_16_R3.ReportedException: Ticking player
	at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:597) ~[patched_1.16.4.jar:git-Paper-345]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:176) ~[patched_1.16.4.jar:git-Paper-345]
	// ...
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_16_R3.WorldServer.fixTileEntity(WorldServer.java:293) ~[patched_1.16.4.jar:git-Paper-345]
	at net.minecraft.server.v1_16_R3.WorldServer.getTileEntity(WorldServer.java:280) ~[patched_1.16.4.jar:git-Paper-345]
	// ...
```

This places a `null`-check on the created tile entity, as it may in fact
be `null`.